add workflows

diff --git a/.github/workflows/snyk-test.yml b/.github/workflows/snyk-test.yml
--- a/.github/workflows/snyk-test.yml
+++ b/.github/workflows/snyk-test.yml
@@ -1,4 +1,4 @@
-name: Snyk Code
+name: Snyk SCA
 
 on:
   push:
@@ -27,6 +27,6 @@ jobs:
         run: |
           npm install snyk -g
           snyk auth ${{secrets.SNYK_AUTH}}
-      - name: Snyk Code # Remove || true to fail if there are vulnerabilities
+      - name: Snyk SCA # Remove || true to fail if there are vulnerabilities
         run: |
-          snyk code test
+          snyk test --severity-threshold=high  
